Repository shophubkr/shophub-client, pull requests merged in 2024-01, with the labels that each got.

#40 회원가입에 필요한 입력 정보는 서버 통신에 맞게 수정하고, 그렇지 않은 정보는 삭제 하였습니다.
  apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
  apps/client/src/app/auth/_components/Form/index.ts
  apps/client/src/app/auth/_components/index.ts
  apps/client/src/app/auth/_constants/validation/index.ts
  apps/client/src/app/auth/_constants/validation/validationMessages.ts
  apps/client/src/app/auth/_constants/validation/validationRegex.ts
  apps/client/src/app/auth/_constants/validation/validationSchemas.ts
  apps/client/src/app/auth/_state/server/api.ts
  apps/client/src/app/auth/_types/index.ts
  apps/client/src/app/auth/_types/signUpType.ts
  apps/client/src/app/auth/signup/step1/page.tsx
  apps/client/src/app/auth/signup/step2/page.tsx
Labels: chore

#35 Detail 페이지 퍼블리싱 1차 마무리
  apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
  apps/client/src/app/shop/[shopid]/_components/CouponSection/index.ts
  apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
  apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/index.ts
  apps/client/src/app/shop/[shopid]/_components/ShopOperationInfo/ShopOperationInfo.tsx
  apps/client/src/app/shop/[shopid]/_components/ShopOperationInfo/index.ts
  apps/client/src/app/shop/[shopid]/_components/ShopProduct/ShopProduct.tsx
  apps/client/src/app/shop/[shopid]/_components/ShopProduct/ShopProduct.types.ts
  apps/client/src/app/shop/[shopid]/_components/ShopProduct/index.ts
  apps/client/src/app/shop/[shopid]/_components/ShopProductSection/ShopProductSection.tsx
  apps/client/src/app/shop/[shopid]/_components/ShopProductSection/index.ts
  apps/client/src/app/shop/[shopid]/_components/index.ts
  apps/client/src/app/shop/[shopid]/layout.tsx
  apps/client/src/app/shop/[shopid]/page.tsx
  apps/client/src/components/Icon/Icon.stories.tsx
  apps/client/src/components/Icon/Icon.tsx
  apps/client/src/components/Icon/Icon.types.ts
  apps/client/src/components/Icon/index.ts
  apps/client/src/components/ImageBox/ImageBox.stories.tsx
  apps/client/src/components/ImageBox/ImageBox.tsx
  apps/client/src/components/ImageBox/ImageBox.types.ts
  apps/client/src/components/ImageBox/index.ts
  apps/client/src/components/index.ts
Labels: publishing

#41 Form에서 사용하는 입력 필드인 FormElement 컴포넌트를 업데이트 합니다.
  apps/client/src/components/Form/FormElement.tsx
  apps/client/src/components/Form/FormProps.type.ts
Labels: chore

#46 rewrite 적용, interceptor하여 return 하는 데이터 형식 수정, 로그인 시 cookie 세팅하는 로직 추가했습니다.
  .pnp.cjs
  .yarn/cache/js-cookie-npm-3.0.5-8fc8fcc9b4-2dbd2809c6.zip
  apps/client/next.config.js
  apps/client/package.json
  apps/client/src/app/auth/_state/server/api.ts
  apps/client/src/app/auth/login/page.tsx
  apps/client/src/app/shared/server/axios/axios.ts
  apps/client/src/app/shared/server/axios/axios.types.ts
  yarn.lock
Labels: feature

#49 이미지 도메인 로드 에러 수정
  apps/client/next.config.js
Labels: fix
